---
title: "Chapter Six: An Island, Three Kayaks and an Inflatable Monkey"
author: "Aaron Honig"
date: "September 16, 2015"
output: html_document
---

CHAPTER VI: An Island, Three Kayaks and an Inflatable Monkey

  We began paddling faster, desperate to reach the long narrow channel of
Catalina Harbor before the night fell into complete darkness. As we made
our way towards the far dim lights of the Harbor’s tiny hamlet, green sparks
suddenly exploded beneath our dark kayaks. For a while, the rhythmic swinging 
of our long paddles had triggered glowing emerald lights from the myriad 
phytoplankton hidden within the waters of the dark sea. But now, long twisting 
spirals of green helices swirled around our the dark shadows of our boats, 
lighting up the surrounding waters. Unsure of what beautiful unseen life we 
had now disturbed, we continued around the large mountainous cape of Cat Head 
and entered the harbor for the first time in our lives. 
 
 In the near-perfect darkness, a few dim lights were scattered across
the cove from several boats anchored in its shallow waters. We kayaked on,
peering forward into the inky void, trying to find safe harbor for the night.
And that’s when we all looked up, high into the night sky, and saw a thirty
ft. tall ship being hurled into fifty ft. tall crashing waves, its yellow-slickered
crew yelling to each other in the roaring maelstrom. 
  
  We looked at each other, silently screaming, “What the fuck?!” as we glanced 
back up at this floating battle between men and sea. We cautiously kayaked forwards 
towards this phantasmagorical apparition, unsure if we were all seeing what we thought
we were all seeing. Couldn’t be. 
  
  As we gently dipped our paddles in the water, unable to take our eyes from the scene
playing out above us, the slender bows of our kayak glided through the still
dark waters of the harbor and with three loud thuds in rhythmic succession, collided 
with fifteen feet of vertical solid wood paneling. Our necks suddenly collapsed to gaze 
into the darkness two feet in front of us, trying to see what we had run into.
  
  From above this rampart of wooden hull, a head suddenly stuck out from the carved banister.

“Hey yall! What’re you guys doin’ here?! Great to see you!”, called out a deep southern accent.

  Incredulously, we looked up to see one of our close friends peering over the side of the ship.

“Hey yall! We’re just about to serve dinner! Come on up!”

  After almost thirty miles of ocean kayaking through huge swell and choking kelp canopies, 
after rounding the farthest, most rugged West Tip of the island aboard bulky sit-on-top
kayaks with no back support, weighted down with 3 days of food, water and gear, dinner 
sounded magical. We tied our bowlines to the side of the ship and hauled our wasted bodies 
up the short side-ladder and aboard, into cozy haven for the remainder of the evening
amongst unforeseen hospitality and close friends. We were safe.

  In the fall of 2007, Brandon, James and I embarked on a kayak adventure 
the likes of which we had never previously attempted. We would circumnavigate 
the whole of Santa Catalina Island, almost sixty miles in three days. Leaving 
our home at Long Point, we would kayak northwest, camping somewhere between Parson’s
Landing and Catalina Harbor, wherever we later decided. From there, a short half-day 
paddle should take us to the secret beach campsite of Salta Verde amidst steep rocky 
embankments and crashing waves beside thousand-foot sea cliffs. Camping here for the 
night would set us up nicely for the last day’s haul around the East End, Seal
Rocks, past the wide bay before the city of Avalon and home to Fox Landing,
inside the peninsula of the widest stretch of Santa Catalina Island.

  After preparing for days, setting up food stores, packing gear and poring over
sea charts and island topographic maps, we couldn’t wait to head out. A few
of our friends had previously circumnavigated the island, and we had
jumped at this narrow window of opportunity to join this select group of
historic island adventurers in this unique and difficult achievement.

  The morning of the launch finally came. Have breakfast, load the boats,
and head out early, beyond the calm protected waters of our cove. Hah. Life
is what happens to you while you’re busy making other plans. We got word
early that Ross Turner, the founder and owner of Guided Discoveries, our
company, was coming out to the island for an important meeting with all of the
island staff. We put all of our stuff together along the beach so we could
leave as soon as possible, and prepared for the meeting with the head of the
company. We filed in and sat down before listening to detailed plans for the
future of Catalina Island Marine Institute. Certain maintenance projects,
expansion of living units and classroom space, etc. He announced
that we would be improving our image by infusing a “tropical ship-wrecked”
Disney-like theme to our cove. Oh, and no one was to use the term FMF any
more, ever. It was divisive against the other teaching facilities outside Fox
Landing, and we were all supposed to be a single united company.

  FMF, of course, stood for the Fox Mafia Family, the historic kindred
which Godfather Chase united into the sacred order of scientists, teachers 
and all-around bad-ass adventurers of Fox Landing, to which we all belonged. 
The FMF was, and always will be, the bonds of friendship and love which tether 
us all together, wherever Foxies may be. We just sat there, silently, knowing 
that the FMF is something sacred which will never die, even if it became taboo 
in certain circles.

  Even more determined now to kick some serious ass and embark on an
unprecedented adventure in the name of true Foxies everywhere, we walked
back down to the beach and strapped down the last of our gear. 

“One last thing, guys”, I said. “Forgot one thing.” 

  I ran up the canyon and back up to my cabin. A few minutes later I
sprinted back down the hill to the beach, smiling broadly and holding a
three ft. tall inflatable monkey covered in green body-paint, a holdover from
some of the festive summer-camp decorations in camp. 

“Pedro’s coming too!” 

  I quickly strapped the monkey atop the back half of the kayak, wearing
the bright yellow life-jacket which, by law, had to be somewhere aboard the
kayak. 

“We all set?” “Yup, yup! Let’s go!” 

  We pulled our bright pink kayaks down to the water’s edge, hopped in our boats 
and slid into the sea amidst the waves. A half-hour later, we pulled our kayaks
back on shore and unloaded some of the heaviest gear, which made our kayaks difficult 
to paddle the few miles we had gone, let alone sixty which would required by journeys end.
But finally, finally we left for good, probably by around 10:30, 11 a.m. at this
point. We turned the corner around the craggy peninsula of Long Point and paddled into the west, towards the horizon. 

  After crossing the small dimple of Long Point Beach, the cliffs gave way towards 
the huge bay of Italian Gardens and its end at Twin Rocks and the bald eagles’ nest. 
All of these familiar places sailed swiftly by as we surged towards the faded peaks 
and rugged coastline far into the distant mists. Today we’d go farther than we’d ever gone.

  Occasionally I’d stop to take photographs of brown pelicans perched along the rocky shore, 
and glittering pools of kelp beckoning my kayak into adjacent sea-caves lined with shore-crabs crawling up and down their sheer walls. Brandon and James would often go far ahead as I
explored the coasts, then caught up to them to go over the maps and mark our progress. Goat
Harbor, Cabrillo, Gibraltar, Ripper’s Cove and Empire Landing were all swept
behind, reflected in the tiny whirlpools formed in the currents of our swinging paddles as we continued on, determined to cover miles during the tropical heat early fall in California.

  The tall eroded terraces of the old quarry stretched beside us while we rounded its corner,
enjoying the beautiful day and our own joyful power, our strength and prowess at traveling so
far in so short a time along such a magnificent coastline. As we approached the wide windswept 
bay of Isthmus Cove just past our current respite at Blue Caverns and Sea-Fan Grotto, I glanced back at Pedro, still clinging to the back of my kayak, grinning broadly back at me with a frozen maniacal stare, a vertical green arrow lining his brown plastic forehead. 

“Here we go!” 

  I kayaked forward with James and Brandon and entered into the wind. While previously sheltered against the tall mountainous coastline and rocky promontories from the worst of the wind, now we entered into unprotected waters, rough seas and strong winds roaring around the spherical mass of
Bird Rock and the tall spire of Ship Rock outside of Two Harbors. I pulled the sea along the side of the kayak, struggling west towards the more protected shelter of 4th of July Cove and Cherry Cove, where a few friends and fellow teachers dwelled.

  Unfortunately, Pedro wasn’t much help. Still largely inflated, this beloved monkey was now acting like a sail, blowing the back of my kayak out to sea with every forward stroke. I 
constantly had to change direction to keep the isthmus in my sights as I fought the wind. As I worked, I glanced right to see the white, guano-encrusted mass of Bird Rock slip by, and joined Brandon and James ahead just outside town. We kept going, finally reaching the protected
shoreline and mooring cans of 4th of July Cove before kayaking through a field of crowded yachts tucked inside the bay of Cherry Cove.

  We carefully pulled our kayaks up onto the pebbly shore and stretched our numb, idle legs. Although there was no one around, we walked up the canyon to say hello to the Cherries,
who we had often worked with in the past. Although we had met a few Cherries previously, 
and were friends,none of us had ever been to Cherry Cove before and we wandered up the
broad road through the canyon, unsure of what to expect. After a long path, a large building appeared to our right which we later learned was the cafeteria. There we met some of our
friends, who welcomed us in for a late lunch if we wanted it. It was about 2:30 in the afternoon at this point, and we were fairly hungry, having not eaten since 8 or so before paddling
nine miles against wind and waves. But we also wanted to make some more distance, so we said our goodbyes and headed out again into the sea.

  Cherry Cove was perhaps a solid day’s kayak from the beach where we had begun the day, at Fox Landing. If we wanted to, we could have turned around and made it back home before nightfall. And we’d be going with the weather. To warm beds, great friends and plenty of cold beer. This was
indeed, the fabled point of no return. But there was never any question, among each other or within the quiet sanctuary of our own minds. We were on a great adventure, and bound to see it through to the end, as are all Foxies who find themselves On The Road and Into The Wild.

  We made our way around the promontory of Lion’s Head and continued west, determined to reach 
the West Tip and outlast this rugged stretch of island. We gazed in wonder at previously unseen territory, broad hills rising westward to a higher central ridge and what must be Silver Peak, 
the West End’s highest mount. Twice we thought the West Tip was upon us, only to reveal several more miles of coastline in the foggy distance.

  The widest tip of the West End was Arrow Point, and though it seemed like the last stretch of land, in truth it was only the halfway mark to the true West Tip. We pushed on through the late afternoon, watching the sun disappear behind the tall ridges to the west. Ahead, a huge cargo-ship drifted along the far horizon beginning its fourmonth journey across the Pacific Ocean on its way to Asian markets. We weren’t going quite that far, but I thought I knew how the crew of that
ship must have felt just before we reached the rough, rocky wave-swept spit and the end of Santa Catalina Island.

  I paddled closer to the rocks, my kayak bouncing up and down through four ft. swell as I tried to snap a few photographs of the West Tip. Looking out carefully for the West Tip light-beacon and the bald eagles’ nest somewhere nearby, we made our way past the crashing waves and into the unknown western backside of the island. We paddled together as a raft and went over our
options. From our map, it seemed like we could either turn around and camp for the night at
Starlight Beach, or keep going and camp somewhere along one of the many inlets between the West Tip and Catalina Harbor, the backside cove of Two Harbors. We decided to press on,convinced that there must be some beach along the coastline which might fulfill our flexible definition of
a safe and cozy bed. 

Ha.

  In these early evening hours we kayaked on, now hampered by having to travel over dense kelp forest cañopies, the flat blades of our paddles catching entangled vines and blades of the thick marine vegetation. Past several small bays, we realized that many of the beaches which were marked on our map were in fact desolate boulder-fields on which it would be hard to land several kayaks, let alone find a flat area of ground to sleep on. We pressed on, determined to find a safe
anchorage before dusk gave way to night. 

  Past the beautiful white bands of Ribbon Rock and the rugged rocks of Lobster Bay, we made our way towards Cat Head around which, we realized too late, we must kayak in order to make
camp on the broad soft sands of the isthmus and Two Harbors. It was around 8:30 that we finally crossed this last barrier to safe haven, as dusk gave way to dark night. 

  While we had detailed maps and charts, none of us had ever been to this Cat Harbor previously and we had no idea what to expect. Knowing the danger we were in, kayaking at night without light, we quickly broke into our dry-bags and donned headlamps, hoping that any passing ships would see us amidst the gloom. We peered forward through the darkening air, hoping to find some way onto the harbors beach. But few lights revealed the extent and shape of what the maps revealed was a long
and narrow cove.

  As our eyes tried to adjust to our inky environment, suddenly bright lights shone high into the night sky, showing some sort of sailing schooner fighting rough seas. Curious and incredulous, we approached the bizarre light-show only to inadvertently kayak into a large wooden ship,
seemingly directly below the shimmering lights. A voice rang out from above the deck, welcoming us to Cat Harbor. 

  It took us a few shocked moments to realize who it was: our good friend Katie Dyal, who
was a sailor aboard the teaching vessel, the Tole Mour, owned by Guided Discoveries, the company
which controlled our own teaching institute of CIMI. We quickly tied our boats to the Tole and climbed aboard, amidst a deck full of young students who were in the middle of watching a short film on historic shipwrecks being projected onto one of the larger sails of the tall ship.

  Smelling hot food, we made our way towards the galley and safe haven. Laughing tiredly at
each other and our good fortune at finding friends, food and shelter in such surprising fashion, we settled in for the night atop the stern deck and wearily fell asleep to the sounds of crashing waves, cracking hulls and drowning men. A good day.

  We woke up to the sound of the giant engine rumbling, and word that the ship would be setting off south for Shark Harbor soon. We gathered our gear and loaded the kayaks, preparing to
take leave of our friends’ great hospitality and kindness. We settled our bodies atop our untied boats and set off in the early morning after grabbing a quick breakfast from the galley.

  As the Tole sped off down the coastline out of Cat Harbor, we followed her wake and made our own
way south towards Little Harbor, Shark Harbor, and eventually to Salta Verde, our destination for the day. Starting our paddle so early in the morning felt great. As sore as we were from the previous day, the gentle sway of the sea’s swell peacefully rolled us towards the twin
coves of Little and Shark Harbors. Knowing that we only had to cover half of yesterday’s distance before setting camp, we relaxingly slipped down the coast beside tall sea-cliffs and around
the corner into Little Harbor.

  We let our kayaks drift inward with the rolling swell towards the officialcampground at the harbor’s shores and pulled our boats up the sandy berm with relative ease. Walking through
grassy campsites with fire pits beside tall groves of swaying palm fronds, we stopped here for a short time to refill our water-bottles and stretch our legs on stable dry ground. Digging my toes
into the soft beach, I stretched out on my back as James went to one of the on-site bathrooms, just enjoying the relaxing morning and serene, protected waters of Little Harbor.

  We climbed back into our boats and continued down the coast, past the Whale’s Tail promontory marking the beginning of Shark Harbor and the several fin-like rocks which jut out of the water, as if one of these fearsome predators lurked just below the harbor’s large waves. Waving
goodbye to the anchored Tole’s crew just outside the bay, we continued past the small Cottonwood Beach and past Sentinel Rock to the larger bay of Ben Weston Beach.

  This was one of the favorite camping and surfing spots of the CIMI staff; large waves 
consistently hammered the wide, sandy beach, outfitted with a wooden table shaded
with palm fronds and several makeshift fire-pits. We slid closer to the beach, wary of the largest
breaking waves which could easily roll all three of us simultaneously. Here was a good time for a strategy session; we knew that our campsite at Salta Verde had even bigger waves than these massive breakers, on a far more dangerously rocky shore. 

  We decided that timing was everything; just go in slowly, then land right after the biggest wave in a series and pull the kayak up the beach fast before the next one washed over your head. We
continued down the coast to Salta Verde, across some of the most remote coastline on the island.
A vast array of ridges and peaks now lay between our kayaks and our beloved home, Fox
Landing at Long Point, across the widest breadth of the entire island.

  We glanced at our maps, trying to match prominent rock features with named places: Ben Weston
Point, China Point, Indian Rock. I still swear Ben Weston Point looks exactly like a bear’s face. Totally missed opportunity there. 

  After a long stretch of coast, we finally made our way around the flat triangular plateau of
Salta Verde Point, and towards its far beach. We gazed around at the pastel turquoise water, discolored by the turbulent mixing of the currents and crashing waves surrounding us. We
continued paddling past Salta Verde for in order to witness the large gorge ofSilver Canyon and its outlet to the sea, to see if there was place to camp there. Awed by this magnificent stretch of coast, we simply let ourselves roll up and down through the swell, gazing upat 1600 ft. peaks and a series of triangular sea-cliffs stretching off to the southern horizon amidst the crashing sounds of eight ft. breaking waves on steep rocky embankments, shaking the ground. 

  After traveling around and throughout the entire island, Salta Verde is still my favorite
beach. It is rugged and beautiful and savage. So wild.

  In the end, we decided to head back to Salta Verde Beach, where we knew there was an established
campsite, what appeared to be a large cache of supplies beside a cracked and broken road running from the beach up into the far hills. Resting our kayaks offshore, we sat for a while, watching the waves, guessing at their intervals, gauging their strength and speed as we prepared to enter their realm. 

  Finally we set out, Brandon first, as we approached the shore. After one of the largest waves
hammered the beach, strong enough for its energy to reflect back and crash seaward into the incoming swell, he paddled forward quickly, jumping out of his kayak as fist-size rocks
were pulled strongly offshore with the undertow of the next big breaker. 

“Go! Go! Go!”, James and I yelled as we watched him drag his kayak up the steep embankment, just as the next big wave collapsed below him, spraying its waters over his head and showering him and his boat. 

  We looked at each other, laughing nervously. 
  
  “Here goes nothin’.”

I headed out, trying to time my paddle with the large swell headed onshore. I followed the biggest wave onshore, and drove hard up onto shore as fast as I could. Not looking back, I jumped out of my kayak and pulled its weight up the first of a series of three steep rocky embankments, desperately trying to get out of the dangerous surf-zone. Just as the next large wave broke on the diagonal embankment below me, I hauled the kayak over the berm’s lip and collapsed onto the flat ledge, getting soaked with the crashing waves spray over my head. 

  As James made his way towards shore, Brandon and I carefully walked down the loose rocky
beach to help pull his kayak up out of the shadow of the breaking waves. With great timing and teamwork, we pulled the kayak up to join the other two atop the beach and looked around at our camp for the night.

  We had arrived at the site early in the afternoon, giving us most of the day to explore the beach, maybe go for a hike up into the hills to get a better view of the surrounding area. After
unpacking our kayaks, we headed up a steep trail which climbed above the beach and to a larger dirt road. Gazing across the wide open sea, we thought we could almost see San Clemente
Island, twenty miles to the south. Maybe. 

  Brandon mentioned that he wanted to check out Silver Canyon and started down. James and I made our way back towards camp to dig through some of our supplies, pulling out a few snacks and beers. I went off to explore the tide-pools for a while, scaling up and down large boulders as James began setting up a fire. A few hours later we all came back to camp and settled around the small fire, watching the sun fall towards the sea’s horizon, marveling at the dusk’s peaceful 
tranquility amidst sea’s rhythmic violence against the crashing shore. 

  We contentedly wondered at our own fortune at being here, together in this place, strong enough
individually and together to make it this far along the island’s coastal wilderness, to enjoy this warm fireside amongst close friends in this beautiful world. Another great day.

  We woke again early, determined to set out and reach the tip of the East End and perhaps even Avalon before midday. But first, the launch.

  We carried our kayaks down to the edge of the first embankment and watched the tall wave sets crash, trying to once again decipher its rhythm.

  Ok. Time to boogie. 
  
  James got in his kayak first, as Brandon and I grabbed its sides and shoved him into the sea, after a particularly large wave. He kayaked forward with all his might, distancing
himself from the imminent explosion. We shouted encouragement as the bow of his kayak rose above his own head, striving towards the top of the wave crest, urging it forward. With a cheer,
he finally rose over the incoming wave as it continued onshore with a deafening crash that made the rocks below our feet tremble slightly.

  I watched Brandon get set up and pushed him hard into the trough of a collapsed wave as he easily slid over a smaller incoming swell, joining James out in the water. And then there was
one. I held my kayak steady while waiting for a break in the incoming surge. When I sensed my time had come, I shoved my kayak forward and jumped inside, landing on my knees as I paddled
furiously, desperate to scale the incoming wall of water in front of me before it hurled me backwards into the rocks. Just as the lip of the wave began to curl, the bow of my kayak
punched through the thin veneer of water and into the calm sea on the far side. We were through.

  We paddled on down the coast, as the constant violence of the shore churned the waters into a turquoise murkiness that was simultaneously beautiful and savage. We passed Church Rock and beneath the small unlit beacon of the East End Light, closing in on Seal Rocks. Indeed, over
the last mile or so we had begun to notice several California sea lions bobbing up and down in the surge, carefully watching the progress of our conspicuously pink vessels. 

  As our kayaks neared Seal Rocks, we began hearing muffled roars, soft at first then growing louder. I looked to my left at the far beach and saw dozens of sea lions lying on its rocks,
pups crawling over each other, bigger males rearing up and barking at each other then settling with a heavy thump back down onto the beach. It was quite a sight.

  We watched several younger females playfully jump in and out of the water around our kayaks as we made our way around the East End. Some of the larger territorial males watched warily, but we carefully avoided drawing too close to shore knowing that a large male could easily knock one of our small kayaks upside down into the milky water. 
    
    Still relatively early, we kayaked faster past the ruined mountainous terraces of the quarry before giving way to the heliport and finally reaching the wide bay outside of the island capital city of Avalon. Seeing the time, we noted that it was definitely possible to reach Toyon Bay by noon, perhaps even make it home during lunch. Why not go for it?

  Unfortunately, this last stretch proved to be some of the toughest paddling of the entire trip. Against the full brunt of the island’s strong winds which typically blow southeast down
the coast, we paddled fiercely against gusts, unprotected by any peninsula or cove. We hauled ourselves forward past familiar coastline, beyond Frog Rock and Gallagher’s Cove. We strove
harder against the weather, trying to reach the sandy shores of Toyon Bay, another of our company’s sites, towards a brief respite from the grueling wind before the final push home.

  We began paddling into Toyon’s bay, trying to avoid several groups of students who were in the middle of guided snorkels led by several of our friends. We pulled the kayaks up onto the soft sand, drying swiftly after the last surge of tide had receded back into the sea. We walked along the beach and looked at our watches; still 11:30. We could wait and have lunch, or go home.

  After two days and more than fifty miles of kayaking, the choice did not seem very difficult. 
It was time to finish what we had started. Together.

  We slid our kayaks back out of the bay and back into the wind. Coastline along which we had worked, played and lived during the long year now rolled alongside our flanks, beckoning us home.
Triumphantly sensing our victory, we paddled swiftly past Guano Rock,Three Sisters and towards 
the Pier. Visions of our jubilant return had danced before my eyes over the last couple days; rows of friends lining the beach shouting encouragement as we paddled the last stretch of sea, completing our long journey and glorious adventure. But just now, the waterfront was empty; this was all wrong. 

  We let our kayaks drift amidst the tall barnacle-encrusted pilings underneath the pier and simply settled on shore, rocking back and forth in the gentle swell inside our protected bay. 
  
Hmm. All quiet on the western front. Hmm.

  We gingerly stepped out of the kayaks and pulled them higher onto shore. Stretching loudly, we highfived each other, wanting to scream triumphantly but those muscles seem to have stopped functioning after three days of adventure on the high seas. We were home.

  As we walked back through camp, we finally saw a few of our friends walking through camp. 
  
“Oh hey guys! You made it back. Good work!”

  Hey, it wasn’t a parade, but I’ll take it. We laughed and went back to unpacking our gear, putting away our kayaks. Tonight we’d celebrate. Just now it was time for lunch, and a nap.

  In the aftermath of our grand adventure, I look back on those days of struggle, testing the limits of our growing prowess throughout Catalina’s land and sea, and the limits of our own
endurance. We had done it, in nearly record time, and we had survived to tell the tale. Our first circumnavigation had taken us to new and wild shores as the bonds between us teachers and the
island grew stronger, as those same bonds between each of us grew in like measure. 

  The FMF was alive and kicking,as it always had been. Every generation of Foxies sets out to discover the island, each other, and themselves. Every generation has their own legends and
tales. These are ours. We look forward to hearing about yours. Viva la FMF!

"He said that faith is like a glass of water. When you’re young, the glass is small, 
and it’s easy to fill up. But the older you get, the bigger the glass gets, and the same
amount of liquid doesn’t fill it anymore. But periodically, the glass has to be refilled."

YOU MET ME AT A VERY STRANGE TIME IN MY LIFE


CHAPTER V: Introducing Children To The Sea

  I stood tall in my thin black wetsuit beside my young students; three-foot tall Hispanic middle-schoolers dressed in green and blue neoprene, their identical round bellies protruding from the horizontal line, parallel to the shore. 
  
“On the count of three!”, I cried. “One! Two! Three!” 

  Together, holding hands, we rushed into the incoming waves and jumped high into the air, belly-flopping down with several huge splashes, completely immersing ourselves in the refreshingly cold, salty water. 
  
  “OK! Jumping jacks!” 

  I threw my arms wildly into the air, up and down, as they kids joined in with me, heating up that thin later of water inside their wetsuits which would keep them warm during our extended snorkel adventure. 
  
  “Great job! Run in place! Run Run! Run!” 
  
  “Now do the Blue Whale Breach!”

I had taught them this particular maneuver, where we would all jump into the air and land on our side with a big splash, breaching like the biggest animal in the Earth’s history. I gathered them
all together, now excited and laughing, into a large circle, all holding hands.

“Ok”, I said. “Now that we’re all holding hands, I want everyone to slowly let their legs float out in front of them. Ready?” 

Reluctantly trusting their bodies to the strong buoyancy of the wetsuits, we all floated together, rocking in the gentle sway of the waves. These preliminary steps were very important, not only to immerse and warm the kids for our long snorkel, but simply to welcome my students to the
ocean environment, one of the great joys of my own young life. Most of these
kids had never seen the ocean before, let alone knew how to swim. And yet here they were, thirty miles across a deep channel, playing in the shallow waves along the remote shores of a small
island. It’s almost impossible to imagine, growing up in one of the poorest communities of the largest urban center in the country, never leaving a ten-block section of cross-streets and decrepit, broken homes. For these young students and the inspiringly devoted community leaders
and teachers who help raise and educate them, providing futures full of hope and love, their trip to Santa Catalina Island represents a unique opportunity to learn and explore
environments that have simply never been imagined.

  While I teach classes on oceanography and ichthyology, squid anatomy and physiology, and marine
mammals, the most important education these students receive is about themselves and each other.
Learning how to be strong, engaged, playful and laughing human beings immersed in a community of
passionate friends hopelessly devoted to each other, their students and the sea. Learning how to confidently reach out towards new and exciting horizons of thought and experience; I’ve personally led many hundreds of students on night snorkels, something most of my adult friends off-island
have never even considered. Learning about their own vital importance amongst the myriad organic life-forms which enable all life on Earth from the tiny houseplant sitting on your desk to the massive blue whale, 110 ft long and 380,000 lbs. heavy, from the microscopic phytoplankton which
provide the majority of oxygen on which all animals on Earth depend to the large complex wetland ecosystems which naturally filter groundwater and prevent devastating floods. 

  Every single day, it is important to be reminded that we are all connected to something larger than ourselves, part of something organic and alive and wild, brave and unafraid.
These young explorers, surging forwards into an entirely unknown world fraught with potential danger and stunning beauty, remind me of this every day and for that, I am grateful.

"If a child is to keep alive his inborn sense of wonder,
he needs the companionship of at least one adult who
can share it, rediscovering with him the joy,
excitement and mystery of the world we live in."

"We cannot live for ourselves alone. Our lives are
connected by a thousand invisible threads, and along
these sympathetic fibers, our actions run as causes
and return to us as results."

"I have argued in this book that we are human in good
part because of the particular way we affiliate with
other organisms. They are the matrix in which the
human mind originated and is permanently
rooted, and they offer the challenge and freedom
innately sought. To the extent that each person can
feel like a naturalist, the old excitement of the
untrammeled world will be regained. I offer this as
a formula of reenchantment to invigorate poetry
and myth: mysterious and little known organisms
live within walking distance of where you sit.
Splendor awaits in minute proportions."

"The close observer soon discovers that the teacher’s
task is not to implant facts but to place the subject
to be learned in front of the learner and, through
sympathy, emotion, imagination, and patience, to
awaken in the learner the restless drive for answers
and insights which enlarge the personal life and
give it meaning."

"It is the supreme art of the teacher to awaken joy
in creative expression and knowledge."

"The whole art of teaching is only the art of
awakening the natural curiosity of young minds
for the purpose of satisfying it afterwards."

"Must we always teach our children with books?
Let them look at the mountains and the stars up
above. Let them look at the beauty of the waters
and the trees and flowers on earth. They will then
begin to think, and to think is the beginning of a
real education."

"Now I see the secret of making the best persons,
it is to grow in the open air and to eat and sleep with the earth."

"A human being is a part of the whole called by us
universe, a part limited in time and space. He
experiences himself, his thoughts and feeling as
something separated from the rest, a kind of optical
delusion of his consciousness. This delusion is a kind
of prison for us, restricting us to our personal desires
and to affection for a few persons nearest to us. Our
task must be to free ourselves from this prison by
widening our circle of compassion to embrace all
living creatures and the whole of nature in its beauty."

"Keep me away from the wisdom which does not cry,
the philosophy which does not laugh and the
greatness which does not bow before children."

"The teacher who is indeed wise does not bid you to
enter the house of his wisdom but rather leads you to
the threshold of your mind."

"Everybody needs beauty as well as bread, places to
play in and pray in, where nature may heal and
give strength to body and soul."

"The important thing is not to stop questioning.
Curiosity has its own reason for existing. One cannot
help but be in awe when he contemplates the mysteries
of eternity, of life, of the marvelous structure of
reality. It is enough if one tries merely to comprehend
a little of this mystery every day.Never lose a holy curiosity."

"We do not inherit the earth from our ancestors,
we borrow it from our children."

"Let children walk with Nature, let them see the
beautiful blendings and communions of death and
life, their joyous inseparable unity, as taught in woods
and meadows, plains and mountains and streams
of our blessed star, and they will learn that death
is stingless indeed, and as beautiful as life."

"Those who dwell, as scientists or laymen, among the
beauties and mysteries of the earth are never alone
or weary of life."

"To see a world in a grain of sand,
And a heaven in a wild flower,
Hold infinity in the palm of your hand,
An eternity in an hour."

  I waved my kids back on shore and raised my own mask to my mouth, spitting against 
the faceplate, showing them how they should clean their own mask before donning them. I then asked them to sit down on the beach next to their two or threeperson buddy groups and start putting
their feet into the slots of their small forked fins. As I tossed my 18 lb weight belt around my waist, I bent down over each pair, checking fin straps, adjusting mask straps and snorkels, making sure everyone was ready. We were almost there.

  I grabbed a couple boogie boards, ran back into the cold water, feeling it once again creep up my ankles and seep down my beck and started sliding my bare feet into my long bright blue
Mares fins. 

“Ok! Are you guys excited to go snorkeling?! This is going to be awesome!” 

  I heard a muffled cheer of nervous excitement through my tight neoprene hood, protecting my ears from the cold seawater. 
  
“K, I’m going to call each buddy group out at a time, just slowly stand up and walk backwards so you don’t trip on your fins. I’m right here; you’re going to be ok! When you get out here, lower your face in the water to check your mask. I’ll be coming around to make sure everyone’s works ok!
Great job guys! Where’s Buddy Group One, the Blue Dolphins?!”

  Two green and blue round shapes rose off the rocky beach on shaky legs and began walking backwards towards me, into the unknown waters of our cove.

“Great job guys, come towards me, almost there!” 

  Two by two, all of my students slowly approached my boogie board, some hovering alongside as I went over the plan. 
  
  “K guys, there is SO much to see! This is going to be great! First, we’re going to swim 
over the sandy bottom; look down for small rays, checkerboard fish, maybe a big bat ray if
we’re really really lucky! Gotta keep your eyes open and down! Then we’re going to head over to those rocks and enter the Kelp Forest where we’ll see beautiful orange garibaldi and red
sheephead and blue blacksmith and yellow senorita! Do you remember what kind of relationship the blacksmith and senorita have?” 

A few kids raised their hands out of the water and yelled through chattering teeth,
“SYMBIOSIS!” I laughed and congratulated them at remembering this difficult word. 

“Ok guys, lets go!!”

  I began pulling the board as a few of them swam next to me, across the ocean’s surface in search
of its beautiful inhabitants and concealed secrets. A few small kelpbass (AKA checkerboard fish) huddled along the sandy bottom below us, as I scanned the rhythmic sand ripples for tiny
clues revealing the presence of a buried halibut or shovelnose guitarfish or round ray: a small
pulsing operculum, perhaps the edge of a caudal fin rising above scattered grains of sand against light brown smooth skin. Ah! There she was! A bat ray! 

  I held the kids up, and yelled, “There’s a ray down there right below us! This ray is not dangerous, though it has a long spine along its tail! It lives in this sandy environment and it
buries itself to hide from predators! I’m going to dive down to show everyone, so look down, ok?! Ok”

  With a flick of my fins, I rose high above the surface, sinking back down below the waves with
momentum and gravity, and bent forward, diving down to the ocean floor some fifteen ft. below, coming to rest a couple feet away from the half-buried ray. I looked back up at the surface to make sure all the snorkel masks were looking down at me then with a wave of my hand, brushed
layers of sand off the back of the ray,exposing its full body as the kids gasped above me. With my other hand, I gently dug my fingers below the fins of the ray and lifted my hand upwards, raising its body off the sea floor as it started swimming away gently, its long wings undulating up and down as it slid across the bay. Almost out of breath, I let my body float back up to the surface
as I watched the kids still gazing down at the bat ray below, gracefully swimming away into unknown ocean mists. I LOVE my job!

"Dwayne: You know what? Fuck beauty contests.
Life is one fucking beauty contest after another.
School, then college, then work... Fuck that.
And fuck the Air Force Academy.
If I want to fly, I’ll find a way to fly.
You do what you love, and fuck the rest."

  In a single instant, I can recall my single proudest moment as a teacher: an 8th grade school during a terrestrial ecology hike class by the high benches up back-canyon. After beginning my class teaching about island formation and geology, moving though natural colonization by plant
and animal communities, I led my students up the drainage gully, tasting native plants and fruits along the way, passing a mule deer along the hill’s tall flanks. We sat down together by the upper benches, overlooking the entire cove: the broad ocean, Bible Peak, northern cactus-laden slopes
and southern scrub-oak communities. I then concluded my class by having the students think about their time on the island, what their favorite moments were, what they will remember. Then I pulled out a favorite book from my hike pack and had the students read the parts of several characters. 

  Swamiswans and hummingfish and brown barbaloots replaced bald eagles, brown pelicans and great blue herons, garibaldi and leopard sharks, Catalina foxes and bison. We mused together about how special are time here together on the island is, how magical everything these short moments are. 
  
  As my student Max turned the last page of my personal
copy of the Lorax, he began to read:

“But now,” says the Once-ler,
“Now that you’re here,
the word of the Lorax seems perfectly clear.
UNLESS someone like you
cares a whole awful lot,
nothing is going to get better.
It’s not.
“SO...
Catch!” calls the Once-ler.
He lets something fall.
“It’s a Truffula Seed.
It’s the last one of all!
You’re in charge of the last of the Truffula Seeds.
And Truffula Trees are what everyone needs.
Plant a new Truffula. Treat it with care.
Give it clean water. And feed it fresh air.
Grow a forest. Protect it from axes that hack.
Then the Lorax and all of his friends may come back.”

  And a mysterious thing happened as his eyes scanned those beloved lines, as his lips bent to release the air which would be welcomed by all of our willing ears. His voice became a little heavier, and deeper. His speech slowed as the full weight of the ideas, the power behind those arbitrary symbols penetrated years of urban ignorance and apathy. As he finished reading, we
could all tell that he was holding back tears. But there was nothing to be said, because those very emotions were rising from inside all of us within earshot. We had all been affected. The realization that we are responsible for not just ourselves, but the greater whole that we are all
part of, the organic matrix in which we are all embedded which will always be part of ourselves whether or not it is shunned or cherished, that is the single moment of teaching which I
hope will be my legacy, within the labyrinthine stories and legends of a man called Honeybear.

"For in the end it is Catalina Island and its dwellers
that we love, not the FMF’s considerable gifts in
showing them to us. I said once that the world we
chart was there long before us, and I still believe it.
We are great enough magicians to tap into our
most common nightmares, daydreams and twilight
fancies, but we never invented them either: we
found them a place to live, a green alternative to
each day’s madness here in a poisoned world. We
are raised to honor all the wrong explorers and
discoverers -thieves planting flags,
murderers carrying crosses.
Let us at last praise the colonizers of dreams."

  After a particularly strong week while teaching at Cherry Cove where I was on loan, after feeling very proud of myself for the effort and knowledge and intimacy I had brought to my teaching that week, I walked right up to both Erica and Andy, the two oldest fish on
staff, both legends in their own right, and simply said thank you. I told them about how great 
my week was, how well I had taught, and that I wanted them to know that every gift I have as a teacher is because of my time with them and every student that has and will ever benefit through being in one of my classes, has benefited because of what I learned from them, from the old fish
who taught me, who inscribed the tenets of the FMF inside my heart, from the many legends who 
have since moved on but will always leave a part of themselves here at Fox Landing. As Andy
and Stephen Hawking and Isaac Newton like to say, we are all standing upon the shoulders of 
giants. I am grateful for being allowed to experience such a view.

"A perfect blossom is a rare thing,
You could spend your life looking for one.
And it would not be a wasted life."

  My second; sitting with a student on one of the Catalina Island ferries back to the mainland after his three-day trip to the island. This student happened to write a scathing evaluation of one of our teachers, our program, of everything he experienced in class here at CIMI. I
happened to be going over for a small errand I had on the mainland. This young man was full of unyielding passion, of undeniable self-assured intelligence. He did not understand the
life we led on the island, the ideas we shared during class, why we cared so much about an ocean of knowledge that to someone like him, eager to go to law school, seemed completely arbitrary and unimportant in his life.

  So during the two-hour voyage across San Pedro Channel I sat down with him. We talked for a long time, about what he cared about, about his opinions, about why he felt the way that he so passionately did. He was scolded and rebuked for writing this very harsh evaluation, and didn’t
understand why, because to him, he wrote the truth, as best as he knew, what he truly felt about his time on the island. 

  And then he asked me, “Why do YOU care? Why is the ocean important? I don’t understand.”

"You think I’m an ignorant savage
And you’ve been so many places
I guess it must be so
But still I cannot see
If the savage one is me
How can there be so much
that you don’t know?
You don’t know ...

You think you own whatever land you land on
The Earth is just a dead thing you can claim
But I know every rock and tree and creature
Has a life, has a spirit, has a name
You think the only people who are people
Are the people who look and think like you
But if you walk the footsteps of a stranger
You’ll learn things
you never knew you never knew
Have you ever heard the wolf cry
to the blue corn moon
Or asked the grinning bobcat why he grinned?
Can you sing with all
the voices of the mountains?
Can you paint with all the colors of the wind?
Can you paint with all the colors of the wind?
Come run the hidden pine trails of the forest
Come taste the sun-sweet berries of the Earth
Come roll in all the riches all around you
And for once, never wonder what they’re worth
The rainstorm and the river are my brothers
The heron and the otter are my friends
And we are all connected to each other
In a circle, in a hoop that never ends
How high will the sycamore grow?
If you cut it down, then you’ll never know
And you’ll never hear the wolf cry
to the blue corn moon
For whether we are white or copper skinned
We need to sing with all the voices of the mountains
We need to paint with all the colors of the wind
You can own the Earth and still
All you’ll own is Earth until
You can paint with all the colors of the wind"

  And I began talking to this young man, generating all of the best explanations that I could summon at a moment’s notice. From a biological perspective: eighty some percent of all
the oxygen on Earth, thermohaline currents and global climate regulation, possibly the womb from which sprang all life on the planet, the food which feeds much of the world’s growing
population, potential medicines and technologies which are being harvested from venomous cone snails and anchored mussels. All of the animals and plants in the ocean, how all of
them are each important to the grand synthesis of all life on earth. From a personal perspective: how I grew up alongside the ocean, what it meant to me as a child, myself, walking up and down 
the beach in wonder, kayaking into the open waves, new worlds to explore and visit, new life to
contemplate and understand. The stirring beauty and grand diversity of ocean environments, of ocean life, how different, yet still connected to our own hominid ancestry in very revealing
ways. Why HE should care: how he personally is connected to the ocean, how everything we do on the mainland, even in Kansas, affects the ocean through large-scale global systems, atmospheric, and through watersheds, how strongly I felt that everything is connected in both visible and invisible
ways, binds us all together in ways that are scarcely comprehensible, in ways that are ancient and new, incredibly resilient, yet in many ways very fragile and delicate. How even a lawyer is
connected to the large percentage of the Earth’s environments that are almost completely 
inaccessible to current human technologies.

  I wasn’t condescending or antagonistic, just open and expressive, sharing the important things in my life to this student who simply wasn’t aware of his place in everything around him. He turned to me after this long monologue and smiled. 
  
"Man, if someone had told me that three days ago! I missed so much!" 

  He thanked me profusely and we continued chatting more about each of our lives, what we
wanted, hoped for.

"To understand the heart and mind of a person,
look not at what he has already achieved
but at what he aspires to."

  It was a great conversation, and I remember it fondly. This student and I still keep in touch; we talked just last week. He and several of his friends have invited me to their 8th grade graduation this spring; June 4th at 5 PM, and I intend on being there. All of us have spent too much time unplugged from the universe around us. I have missed too much myself. But it’s never too
late to do what’s right. Here’s for lost time!

"I’ve said it before and I’ll say
it again: Life moves pretty fast
If you don’t stop and look around
once in a while, you could miss it."